landingpage/urls.py
from django.urls import path
from . import views


app_name = 'landingpage'

urlpatterns = [
    path('', views.index, name='index'),
    path('berita/',views.berita, name= 'berita'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),

]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
from statistikCovid import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landingpage.urls"), name = "landingpage"),
    path('covidResearch/', include("covidResearch.urls"), name = "covidResearch"),
    path('dampak/', include("dampak.urls"), name = "dampak"),
    path('statistik/', include("statistikCovid.urls"), name = "statistikCovid"),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landingpage/models.py
from django.db import models

landingpage/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

landingpage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def berita(request):
    return render(request, 'home/berita.html')

def logoutUser(request):
    logout(request)
    return redirect('landingpage:index')

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('landingpage:index')

    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('landingpage:index')
            
            else:
                messages.info(request, 'Nama anda atau password anda salah...')
            
    context = {}
    return render(request, 'home/login.html', context)

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('landingpage:index')

    else:    
        form = CreateUserForm()
        if request.method =="POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, "Akun " + user + " sudah dibuat")
                return redirect('landingpage:login')

    context = {'form':form}
    return render(request, 'home/register.html', context)

landingpage/templates/home/berita.html
{% extends "base_template.html" %}
    {% block content %}
    {% load static %}

<!---Berita Korona -->
<h1 style="margin-top: 40px;">Berita Hari Ini</h1>

<div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>

  <div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>
  
<div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>

<!---Jumbotron -->
<div class="jumbotron jumbotron-fluid" style="margin-top: 40px; background-color: #EB5757; color: white;">
    <div class="container">
        <p class="lead" style="float: left;";><b>Ingin terus update dengan berita terbaru mengenai virus Corona</b></p>
        <a href="{% url 'landingpage:register' %}" class="btn btn-primary" style="float: right;" target="_blank">Klik untuk Berlangganan</a>
    </div>
</div> 

{% endblock %}

landingpage/templates/home/index.html
{% extends "base_template.html" %}
    {% block content %}
    {% load static %}


        {% if user.is_authenticated %}
        <div style="float: left;">
        <p style="float: left;"> Selamat datang {{ request.user.username }}! </p>
        <a class="btn btn-primary btn-lg" href="{% url 'landingpage:logout' %}" style="float: right;">Logout</a>
        </div>
        {% endif %}

        
 


    <div class="container-fluid padding" style="margin-top:90px; ">
        <div class="row padding">
            <div class="col-md-12 col-lg-7">
                <h1>Virus Corona</h1>
                <p>Coronavirus (CoV) adalah keluarga besar virus yang menyebabkan penyakit mulai
                    dari gejala ringan sampai berat. Ada setidaknya dua jenis coronavirus yang diketahui
                    menyebabkan penyakit yang dapat menimbulkan gejala berat seperti Middle East Respiratory Syndrome (MERS-CoV) dan Severe Acute Respiratory Syndrome (SARS-CoV). Novel coronavirus (2019-nCoV) adalah virus jenis baru yang belum pernah diidentifikasi
                    sebelumnya pada manusia. Virus corona adalah zoonosis (ditularkan antara hewan dan
                    manusia). </p>
                
            </div>
        
            <div class="col-lg-5">
          
            <img src="../../static/home/Virus.png" alt="Ini_Gambar_Virus" width="50%" style="margin-left: 20em;">
            </div>
        </div>
        </div>
     
        
<!---Jumbotron -->
<br><br>
<div class="jumbotron jumbotron-fluid" style="margin-top: 90px; background-color: #EB5757; color: white;">
    <div class="container">
        <p class="lead" style="float: left;";><b>Ingin terus update dengan berita terbaru mengenai virus Corona</b></p>
        <a href="{% url 'landingpage:register' %}" class="btn btn-primary" style="float: right;" target="_blank">Klik untuk Berlangganan</a>
    </div>
</div>


<!---Peta -->
<div class="card">
  <div class="card-body">
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    <h1 class="card-title">Data Penyebaran Corona</h5>
    <p class="card-text">Link Network Graph : <a href="https://app.powerbi.com/view?r=eyJrIjoiMTZhNmY2OTEtMGUxNi00NWNhLThjMzQtZTI1MjQ4NmU5ZDY2IiwidCI6IjVkNWE3MWRkLTk0ZDMtNDM0OC04YzViLWY0MDhiOTUyYjBkMSIsImMiOjEwfQ%3D%3D">Ini</a></p>
    
    <div class="row">
      <div class="col-sm-4" style="background-color: #EB5757;">
      <br>
      <h2>Kasus Meninggal</h2>
      <h3>15.037</h3>
      <br>
    </div>
      
    <div class="col-sm-4" style="background-color: #FDD262;">
      <br>
      <h2>Kasus Positif</h2>
      <h3>457.735</h3>
      <br>
    </div>


    <div class="col-sm-4" style="background-color: #0ACF83;">
      <br>
      <h2>Kasus Positif</h2>
      <h3>385.094</h3>
      <br>
    </div>
    
  </div>
  </div>
  <img class="card-img-bottom" src="../../static/home/indonesia.jpg" alt="Card image cap">



</div>

<!---Berita Korona -->

<h1 style="margin-top: 40px;">Berita Corona</h1>
<br>

<div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>

  <center><a href="{% url 'landingpage:berita' %}" class="btn btn-primary" style="margin-top: 40px;">Lihat Berita Lainnya</a></center>

 <!---Jumbotron -->
<div class="jumbotron jumbotron-fluid" style="margin-top: 40px; background-color: #EB5757; color: white;">
    <div class="container">
        <p class="lead" style="float: left;";><b>Ingin terus update dengan berita terbaru mengenai virus Corona</b></p>
        <a href="{% url 'landingpage:register' %}" class="btn btn-primary" style="float: right;" target="_blank">Klik untuk Berlangganan</a>
    </div>
</div> 

  <br><br><br>


{% endblock %}

landingpage/templates/home/login.html
{% extends "base_template.html" %}
{% block content %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    
<center>
    
    <div class="d-flex justify-content-center h-100">
    <div class="user_card">
        <div class="d-flex justify-content-center">


    <h3 id="form-title">MASUK</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
            <form method="POST" action="">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" name="username" placeholder="Nama..." class="form-control">
                </div>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                        <input type="password" name="password" placeholder="Password..." class="form-control" >
                </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                         <input class="btn login_btn" type="submit" value="login">
                       </div>
            </form>

        </div>
        
        {% for message in messages %}
            <p id=messages> {{message}} </p>
        {% endfor %}
        
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                Belum memiliki akun? <a href="{% url 'landingpage:register' %}" class="ml-2">Daftar</a>
            </div>
    
        </div>
    </div>
</div>	

</center>


{% endblock %}

landingpage/templates/home/register.html
{% extends "base_template.html" %}
{% block content %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

<center>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">PENDAFTARAN AKUN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Daftarkan Akun">
				   		</div>
					</form>
                </div>
                
                {{form.errors}}
                
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Sudah memiliki akun? <a href="{% url 'landingpage:login' %}" class="ml-2">Masuk</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</center>

	<script>
	var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nama..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Ketik Password...';
		form_fields[4].placeholder='Ketik Ulang Password...';

		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>

{% endblock %}